version: '3.3'
services:
  db:
    image: mysql:latest
    container_name: OC_Bibliotheque
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'rootbibliothequeroot'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
# Names our volume
volumes:
  my-db:
