version: '3.7'
services:

  Mysql_ouvrage:
    image: mysql:latest
    container_name: "bibliotheque_ouvrage"
    restart: always
    environment:
      MYSQL_DATABASE: 'ouvrage'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'bibliotheque'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'rootbibliotheque'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'rootbibliotheque'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./ouvrage.sql:/docker-entrypoint-initdb.d/ouvrage.sql
      - ./stock.sql:/docker-entrypoint-initdb.d/stock.sql

  Mysql_reservation:
    image: mysql:latest
    container_name: "bibliotheque_reservation"
    restart: always
    environment:
      MYSQL_DATABASE: 'reservation'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'bibliotheque'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'rootbibliotheque'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'rootbibliotheque'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./reservation.sql:/docker-entrypoint-initdb.d/reservation.sql

