version: '3.3'
services:
  db:
    image: mysql:latest
    container_name: OC_Bibliotheque
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'rootbibliothequeroot'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./ouvrage.sql:/docker-entrypoint-initdb.d/ouvrage.sql
      - ./stock.sql:/docker-entrypoint-initdb.d/stock.sql
      - ./utilisateur.sql:/docker-entrypoint-initdb.d/utilisateur.sql
# Names our volume
volumes:
  my-db:
