version: '3.7'
services:
  db:
    image: mysql:latest
    container_name: "mysql_bibliotheque"
    restart: always
    environment:
      MYSQL_DATABASE: 'bibliotheque'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'bibliotheque'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'rootbibliotheque'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'rootbibliotheque'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./livre.sql:/docker-entrypoint-initdb.d/livre.sql
# Names our volume
volumes:
  my-db:
